# Generated by Django 4.2.5 on 2023-09-11 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OderItems',
            new_name='OrderItems',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dateOder',
            new_name='dateOrder',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='oder',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='oder',
            new_name='order',
        ),
    ]
