# Generated by Django 4.2.5 on 2023-09-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_oder_order_rename_oderitems_orderitems_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
