# Generated by Django 4.2.5 on 2023-09-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_product_cost_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
