# Generated by Django 4.2.5 on 2023-09-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile_alter_product_slugname_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='Chưa có', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(blank=True, default='Chưa có', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='sliderhome',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sliders'),
        ),
        migrations.AlterField(
            model_name='sliderhome',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
