# Generated by Django 4.2.5 on 2023-10-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_orderitem_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transactionId',
        ),
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
