# Generated by Django 4.2.5 on 2023-10-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_order_transactionid_order_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phoneNumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
