# Generated by Django 5.0.1 on 2024-04-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_product_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('category0', 'iPhone'), ('category1', 'iPhone cũ'), ('category2', 'Tablet'), ('category3', 'Samsung'), ('category4', 'Oppo - Xiaomi'), ('category5', 'Laptop')], default='category0', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='publisher',
            field=models.IntegerField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
