# Generated by Django 5.0.1 on 2024-04-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_product_category_alter_product_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='publisher',
            new_name='launchYear',
        ),
    ]
