# Generated by Django 5.0.1 on 2024-04-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_publisher_product_launchyear'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SliderHome',
            new_name='Slider',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('category0', 'Chưa phân loại'), ('category1', 'iPhone cũ'), ('category2', 'Tablet'), ('category3', 'Samsung'), ('category4', 'Oppo - Xiaomi'), ('category5', 'Laptop'), ('category6', 'iPhone')], default='category0', max_length=30),
        ),
    ]
