# Generated by Django 5.0.1 on 2024-04-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_sliderhome_slider_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='launchYear',
            field=models.IntegerField(blank=True, default='N/A', null=True),
        ),
    ]
